/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import servicos.ChatServicos;
import utilidades.conversao;


/**
 *
 * @author 182220058
 */
public class GUIChat extends javax.swing.JFrame {
    private  int posicao =50;
    final  JPanel panel = new JPanel();
    /**
     * Creates new form GUIChate
     */
    public GUIChat() {
        initComponents();
        
        
        JScrollPane scroll = new JScrollPane();
        //aqui eu isolo a localiza??o do scrollpane
        scroll.setLocation(10, 11);
        getContentPane().add(scroll);
        //alterei pra final para que fosse possivel
        //chamar o componente dentro da classe anonima
        //do actionPerformed
        
        //aqui defino um boxlayout, e a forma de alinhamento
        //dos componentes, no caso, somente em vertical
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setSize(new Dimension(259, 231));
        //adicionar borda transparente ao painel
        //defini right e left pros botoes n?o ficarem
        //colados na borda
        panel.setBorder(new EmptyBorder(0, 5, 0, 5));
        scroll.setViewportView(panel);
        //vincula o tamanho do panel pro tamanho do scroll
        scroll.setSize(panel.getSize());

       


    }
    
       public static void gerarLabel(JPanel panel,String mensagem,int num) {
           conversao conv = new conversao();
           mensagem = conv.formatacaoMenagem(mensagem,num);
        JLabel label = new JLabel(mensagem);
        //pro bot?o ficar com tamanho maximo no BoxLayout
        // ? preciso definir a dimens?o maxima do botao
        //Integer.MAX_VALUE definir a maior largura possivel
        label.setMaximumSize(new Dimension(Integer.MAX_VALUE, label.getMinimumSize().height));
        //adicionei um espa?amento pro proximo botao n?o
        //ficar colado, voc? pode alterar a vontade
        panel.add(Box.createRigidArea(new Dimension(0, 5)));
         
        panel.add(label);
       
          

         
        //o revalidate deve ser aplicado ao componente root
        //neste caso, o JFrame
        //pra evitar problemas com tamanho de outros containers
        //da tela
        panel.getRootPane().revalidate();
    }
       public void mandarMensagem() throws SQLException{
           ChatServicos cs = new servicos.ServicosFactory().getChatServicos();
           cs.mandarMensagem(jtfMensagem.getText());
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfMensagem = new javax.swing.JTextField();
        jtbEnviar = new javax.swing.JButton();

        jtbEnviar.setText("Enviar");
        jtbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jtfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtbEnviar)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbEnviar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbEnviarActionPerformed
        
        try {
            mandarMensagem();
        } catch (SQLException ex) {
            Logger.getLogger(GUIChat.class.getName()).log(Level.SEVERE, null, ex);
        }
        gerarLabel(panel,jtfMensagem.getText(),0);
        jtfMensagem.setText("");
        getContentPane().repaint();

    }//GEN-LAST:event_jtbEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jtbEnviar;
    private javax.swing.JTextField jtfMensagem;
    // End of variables declaration//GEN-END:variables
}
